### ISSUE TITLE
Closing products doesn't release file

### ISSUE THREAD

**Issue by LupusUmbrae** [senbox-org/snap-desktop#15]
When a product is closed in the SNAP Toolkit the process keeps hold of it preventing any actions on it while SNAP is still running (Windows).

Steps:
1. Open SNAP
1. Open product
1. Close Product
1. Try to delete/move product (This will fail on Windows)
1. Close Snap
1. Try to delete/move product (Will not work)

**Comment by marpet** [comment]
For which products di you experience this. This behaviour is dependent on the re reader.

**Comment by LupusUmbrae** [comment]
I've only tried this for reading NetCDF files. In this case no specific product type.

Just to test it with an actual product i get the same error when using the following file:
ATS_TOA_1PUUPA20120408_020245_000065273113_00261_52861_6803.N1

**Comment by marpet** [comment]
The problem seems to be twofold. For example for ATS_TOA file it works, but we rely on the Java VM and the operating system. You can enable the performance toolbar (View -> Toolbars --> Performance). Now, after closing the product in SNAP and then clicking on the memory graph the file is released immediately. So, maybe we should trigger a garbage collection after products have been closed.
For NetCDF it seems be dependent on the NetCDF library and the file. For some files the handle is released immediately but for others not (NetCDF3). In both cases the appropriate methods are called.
The trick with the memory graph is not working here.

**Comment by LupusUmbrae** [comment]
Here is an image of the error, in this case the three files are two NetCDF 4 files and one XML file. This is on Version 4.0.0 now.

![snap file in use](https://cloud.githubusercontent.com/assets/914585/16731848/32625dda-4772-11e6-8b6b-468fc60fe5c9.PNG)

**Comment by marpet** [comment]
This is fixed on the current master branch.
