### ISSUE TITLE
Suggestion, make GPT graphs editable in the SNAP GUI

### ISSUE THREAD

**Issue by funkenbeachin** [senbox-org/snap-desktop#70]
It would be useful to make GPT graphs editable in the GUI.  Add clear only lines.  Add, rearrange, remove boxes.  Save the result as a new graph.

Processes in radar interferometry graphs can be complicated and sometimes process options are 4 or 5 menu levels deep, so editing the graph once lines are drawn would be nice.

**Comment by marpet** [comment]
I don't really understand your request. Because this all this is already possible. The Graph Builder can be invoked by clikcing on:  ![image](https://user-images.githubusercontent.com/204590/51170699-5a02ff00-18af-11e9-8f8a-f121592e3619.png)

![image](https://user-images.githubusercontent.com/204590/51170667-435ca800-18af-11e9-9ec1-0ffe021b86ca.png)

**Comment by funkenbeachin** [comment]
Once I applied flow lines, I could not remove only the lines.  I had to clear the graph and start over.

If I used right click, connect graph and some lines were incorrect, I can not remove them.  Would like to remove a single line and/or remove all lines.

**Comment by funkenbeachin** [comment]
I would like to edit an existing template, remove lines and blocks, add new blocks and save.

**Comment by funkenbeachin** [comment]
I see that I can remove a box and and a line.  That works.  Thanks.
